# Generated by Django 2.1.2 on 2018-10-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasa_apod_api', '0002_auto_20181013_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasaapod',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nasaapod',
            name='copyright',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
