# Generated by Django 2.1.2 on 2018-10-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune_1000', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='assets',
            field=models.IntegerField(null=True),
        ),
    ]
