# Generated by Django 2.1.2 on 2018-10-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune_1000', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stock_ticker',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='assets',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='market_value',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='revenue',
            field=models.BigIntegerField(null=True),
        ),
    ]
