# Generated by Django 2.1.2 on 2018-10-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune_1000', '0002_auto_20181012_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ceo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='profits',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='stock_ticker',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
