# Generated by Django 2.1.2 on 2018-10-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortune_1000', '0003_auto_20181012_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='stock_ticker',
            new_name='stock_symbol',
        ),
    ]
